apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exofront-ingress
  namespace: exohunter
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  tls:
    - hosts:
        - exohunter.earth
        - '*.exohunter.earth'
      secretName: exofront-tls
  rules:
    - host: '*.exohunter.earth'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: exofront-svc
                port:
                  number: 80

    - host: exohunter.earth
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: exofront-svc
                port:
                  number: 80
